# $FreeBSD$

freebsd_instance:
  image: freebsd-12-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  install_script:
  - pkg install -y
    v4l_compat swig ffmpeg curl dbus fdk-aac fontconfig
    freetype2 jackit jansson luajit mbedtls pulseaudio speexdsp
    libsysinfo libudev-devd libv4l libx264 cmake ninja
    mesa-libs lua52 pkgconf
    qt5-svg qt5-qmake qt5-buildtools qt5-x11extras qt5-xml
  script:
  - mkdir build
  - cd build
  - cmake -DUNIX_STRUCTURE=1 -GNinja ..
  - ninja
