image:
 - Visual Studio 2017

environment:
  CURL_VERSION: 7.56.1
  CEF_VERSION: 3.3440.1805.gbe070f9

install:
  - git submodule update --init --recursive
  - cmd: C:\projects\obs-studio-webrtc\CI\install-script-win.cmd
  - cmd: c:\projects\obs-studio-webrtc\CI\configure-script-win.cmd

build_script:
# - cmake --build . --config Release
  - ctest -D Experimental -C Release
  - cpack

before_deploy:
  - cmd: C:\projects\obs-studio\CI\before-deploy-win.cmd

# deploy:

test: off

cache:
  - dependencies2017.zip
  - vlc.zip
 # right now, we just remove this option which takes otherwise a lot of space
 # - 'cef_binary_%CEF_VERSION%_windows64.zip'
  - Qt_5.10.1.7z
  - libWebRTC-73-win.tar.gz
  - openssl-1.1.zip
