environment:
  matrix:
    - VS: Visual Studio 9 2008
    - VS: Visual Studio 10 2010
    - VS: Visual Studio 11 2012
    - VS: Visual Studio 12 2013
    - VS: Visual Studio 14 2015

build_script:
  - md build
  - cd build
  - cmake -G "%VS%" ..
  - cmake --build . --config Release
  - ctest --output-on-failure
