// Copyright Evercast 2020.

#ifndef OBS_STUDIO_EVERCAST_H
#define OBS_STUDIO_EVERCAST_H

#define EVERCAST_SUCCESS 0
#define EVERCAST_ERR_UNSUPPORTED_AUDIO_CODEC 430
#define EVERCAST_ERR_DUPLICATE_USER 436

#endif //OBS_STUDIO_EVERCAST_H
