name: "Crowdin Sync: Upload English strings"
on:
  push:
    branches:
      - master
    paths:
      - "**/en-US.ini"
jobs:
  crowdin-sync-upload:
    name: Upload English strings
    runs-on: ubuntu-latest
    env:
      CROWDIN_PAT: ${{ secrets.CROWDIN_SYNC_CROWDIN_PAT }}
      GITHUB_EVENT_BEFORE: ${{ github.event.before }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 100
      - uses: obsproject/obs-crowdin-sync/upload@0.2.1
