name: "Crowdin Sync: Import latest translations"
on: workflow_dispatch
jobs:
  crowdin-sync-download:
    name: Import latest translations
    runs-on: ubuntu-latest
    if: github.repository_owner == 'obsproject'
    env:
      CROWDIN_PAT: ${{ secrets.CROWDIN_SYNC_CROWDIN_PAT }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.CROWDIN_SYNC_GITHUB_PAT }}
      - uses: obsproject/obs-crowdin-sync/download@0.2.1
